
#define keyInterrupt 2
#define NOTSET -1

#define speakerPin 13

// Scale in the key of 25000
// Automatically generated by scaleGenerator.py

#include "scale8.h"
#define SPEAKER_DDR       DDRD
#define SPEAKER           PD6           /* OC0A */

#define NOTE_DURATION     0xF000        /* determines long note length */

volatile int row = NOTSET;
volatile int col = NOTSET;

const uint8_t keys[] = { 'A', 'W', 'S', 'E', 'D', 'F', 'T',
  'G', 'Y', 'H', 'J', 'I', 'K', 'O',
  'L', 'P', ';', '\''
};


static inline void playNote(uint8_t wavelength, uint16_t duration) {


  OCR0A = wavelength;                                     /* set pitch */
  SPEAKER_DDR |= (1 << SPEAKER);           /* enable output on speaker */

  delay(duration);

  // while (duration) {                                 /* Variable delay */
  //   _delay_ms(1);
  //   duration--;
  // }
  SPEAKER_DDR &= ~(1 << SPEAKER);                  /* turn speaker off */
}

static inline void initTimer(void) {
  // reset timer 0 control registers
  TCCR0B = 0;  
  TCCR0A = 0;
  
  TCCR0A |= (1 << WGM01);                                  /* CTC mode */
  TCCR0A |= (1 << COM0A0);           /* Toggles pin each cycle through */
  TCCR0B |= (1 << CS00) | (1 << CS01);               /* CPU clock / 64 */
}

inline void initKeypad() {

  pinMode(A0, OUTPUT);
  pinMode(A1, OUTPUT);
  pinMode(A2, OUTPUT);
  pinMode(A3, OUTPUT);

  digitalWrite(A0, LOW);
  digitalWrite(A1, LOW);
  digitalWrite(A2, LOW);
  digitalWrite(A3, LOW);
  
  pinMode(A4, INPUT_PULLUP);
  pinMode(A5, INPUT_PULLUP);
  pinMode(A6, INPUT_PULLUP);
  pinMode(A7, INPUT_PULLUP);

  PCICR |= (1 << PCIE1);
  PCMSK1 |= (1 << PC0) | (1 << PC1) | (1 << PC2) | (1 << PC3);

  // attachInterrupt(digitalPinToInterrupt(keyInterrupt), keypadHandler, LOW);
  
}

void setup() {
  // Open serial communications and wait for port to open:
  initKeypad();
  initTimer();

  pinMode(speakerPin, OUTPUT);
  
  Serial.begin(115200);
  Serial.println("setup");

  interrupts();
}

void loop() {
  if (row != NOTSET) {

    Serial.print("row:");
    Serial.print(row);
    Serial.print(" col: ");
    Serial.println(col);
    
    delay(5); // 5ms

    playNote(A1, 200);


    // switch(row) {
    //   case A4 : {
    //     switch(col) {
    //       case A0 : {
    //         playNote(G3, 200);
    //       }
    //       case A1 : {
    //         playNote(F3, 200);
    //       }
    //       case A2 : {
    //         playNote(E3, 200);
    //       }
    //       case A3 : {
    //         playNote(D3, 200);
    //       }
    //     }
    //   }
    //   case A5 : {
    //     switch(col) {
    //       case A0 : {
    //         playNote(C3, 200);
    //       }
    //       case A1 : {
    //         playNote(Cx3, 200);
    //       }
    //       case A2 : {
    //         playNote(A3, 200);
    //       }
    //       case A3 : {
    //         playNote(G2, 200);
    //       }
    //     }
    //   }
    //   case A6 : {
    //     switch(col) {
    //       case A0 : {
    //         playNote(F2, 200);
    //       }
    //       case A1 : {
    //         playNote(E2, 200);
    //       }
    //       case A2 : {
    //         playNote(D2, 200);
    //       }
    //       case A3 : {
    //         playNote(C2, 200);
    //       }
    //     }
    //   }
    //   case A7 : {
    //     switch(col) {
    //       case A0 : {
    //         playNote(B2, 200);
    //       }
    //       case A1 : {
    //         playNote(A2, 200);
    //       }
    //       case A2 : {
    //         playNote(F1, 200);
    //       }
    //       case A3 : {
    //         playNote(A1, 200);
    //       } 
    //     }
    //   }
    // }

    col = NOTSET;
    row = NOTSET;
  }

  delay(100);
}

ISR(INT1_vect) {
  keypadHandler();
  PCIFR |= (1 << PCIF1);
}

void keypadHandler() {

  noInterrupts();

  // scan rows
  if (digitalRead(A4) == 0) { row = A4; }
  else if (digitalRead(A5) == 0) { row = A5; }
  else if (digitalRead(A6) == 0) { row = A6; }
  else if (digitalRead(A7) == 0) { row = A7; }

  // scan columns
  if (row == NOTSET) return;
  digitalWrite(A0, HIGH);
  if (digitalRead(row) == 1) {
    col = A0;
    digitalWrite(A0, LOW);
    // interrupts();
    return;
  }
  digitalWrite(A0, LOW);

  digitalWrite(A1, HIGH);
  if (digitalRead(row) == 1) {
    col = A1;
    digitalWrite(A1, LOW);
    // interrupts();
    return;
  }
  digitalWrite(A1, LOW);

  digitalWrite(A2, HIGH);
  if (digitalRead(row) == 1) {
    col = A2;
    digitalWrite(A2, LOW);
    // interrupts();
    return;
  }
  digitalWrite(A2, LOW);

  digitalWrite(A3, HIGH);
  if (digitalRead(row) == 1) {
    col = A3;
    digitalWrite(A3, LOW);
    // interrupts();
    return;
  }
  digitalWrite(A3, LOW);

  // logic_error: key was pressed but couldn't figure out which one?

  row = NOTSET;
  col = NOTSET;

  // interrupts();

}
